### ISSUE TITLE
Create search option

### ISSUE THREAD

**Issue by overeha** [code4romania/whos-who#14]
The search should go through the entire content: 
- main navigation titles
- accordion titles
- accordion content

ignore the About page.

**Comment by aniri** [comment]
Related to component issue https://github.com/code4romania/taskforce-fe-components/issues/110 . It would be great to fix the component task first and then reuse it here ;)

**Comment by schesa** [comment]
✋

**Comment by tudoramariei** [comment]
Great job @schesa on finishing code4romania/taskforce-fe-components#110
This issue has no more dependencies left now 🙌

**Comment by tudoramariei** [comment]
To add more details regarding the search functionality:
Since we are placing all the data in _accordion files_ we should highlight the files containing valid search results. The colour used for highlighting should be different from the ones we are using now. It should also be easy to change since we don't have the final colour scheme yet.

**Comment by schesa** [comment]
Hey, this week I will not be able to handle this issue

**Comment by tudoramariei** [comment]
Moved this back to todo. If someone is available to work on this issue these days, don't be shy, just say hi 😄

**Comment by cipick** [comment]
✋
